### ISSUE TITLE
Pin ecosystem version

### ISSUE THREAD

**Issue by antonagestam** [antonagestam/goose#111]
Pinning the ecosystem version will allow omitting the specification of versions in the ecosystem definition.

On upgrade there will be some semantics for picking the highest available stable version.

This also means it can be considered to allow a short-form definition. Instead of the verbose:

```yaml
environments:
  - id: python
    ecosystem:
      language: python
      version: "3.13"
```

This can be shortened to:

```yaml
environments:
  - id: python
    ecosystem: python
```
